import React from 'react';
import {
  Bot,
  Settings,
  SquareLibrary,
  type LucideIcon,
  TestTubeDiagonal,
  Send,
  ChevronUp,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  X,
  Rocket,
  Mail,
  BookOpen,
  Plug,
  Notebook,
  Monitor,
  Info,
  Trash2,
  CirclePause,
  User,
  Brain,
  Plus,
  Trash,
  Key,
  LogOut,
  PartyPopper
} from 'lucide-react';
import { NotionIcon } from './NotionIcon';
import { IconName } from "./Icon.types";
import { GoogleIcon } from './GoogleIcon';

export const iconMapper: Record<IconName, LucideIcon | React.FC> = {
  bot: Bot,
  settings: Settings,
  'test-tubes': TestTubeDiagonal,
  'square-library': SquareLibrary,
  send: Send,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  x: X,
  rocket: Rocket,
  mailbox: Mail,
  'book-open': BookOpen,
  plug: Plug,
  notebook: Notebook,
  monitor: Monitor,
  info: Info,
  'trash-2': Trash2,
  'circle-pause': CirclePause,
  user: User,
  brain: Brain,
  plus: Plus,
  trash: Trash,
  key: Key,
  logout: LogOut,
  notion: NotionIcon,
  google: GoogleIcon,
  "party-popper": PartyPopper
};