import {
  Bot,
  Settings,
  SquareLibrary,
  type LucideIcon,
  TestTubeDiagonal,
  Send,
  ChevronUp,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  X,
  Rocket,
  Mail,
  BookOpen,
  Plug,
  Notebook,
  Monitor,
  Info,
  Trash2,
  CirclePause
} from 'lucide-react';
import { IconName } from "./Icon.types";

export const iconMapper: Record<IconName, LucideIcon> = {
  bot: Bot,
  settings: Settings,
  'test-tubes': TestTubeDiagonal,
  'square-library': SquareLibrary,
  send: Send,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  x: X,
  rocket: Rocket,
  mailbox: Mail,
  'book-open': BookOpen,
  plug: Plug,
  notebook: Notebook,
  monitor: Monitor,
  info: Info,
  'trash-2': Trash2,
  'circle-pause': CirclePause
};